form-flow:
  inputs: 'org.formflowstartertemplate.app.inputs.'
  uploads:
    accepted-file-types: '.jpeg,.jpg,.png,.pdf,.bmp,.gif,.doc,.docx,.odt,.ods,.odp,.heic'
    thumbnail-width: '64'
    thumbnail-height: '60'
    max-files: '20' # 20 files maximum
    max-file-size: '20' # 20 MB file size limit
  aws:
    region: 'us-west-1'
    s3_bucket_name: 'child-care-illinois'
    access_key: ${AWS_ACCESS_KEY}
    secret_key: ${AWS_SECRET_KEY}
spring:
  profiles:
    group:
      test:
        - test
        - form-flow-library-test
      dev:
        - dev
        - form-flow-library
      demo:
        - demo
        - form-flow-library
  thymeleaf:
    cache: false
    template-resolver-order: 0
    check-template-location: true
  # TODO: move caching 0 to a dev only context?
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
  datasource:
    url: jdbc:postgresql://localhost:5432/child-care-model-illinois
    username: child-care-model-illinois
    password:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
logging:
  level:
    root: INFO
    org.springframework.web: ERROR
server:
  tomcat:
    max-http-form-post-size: 20MB
