name: childcare
conditionsPath: org.formflowstartertemplate.app.submission.conditions
actionsPath: org.formflowstartertemplate.app.submission.actions
flow:
  basicInfo:
    nextScreens:
      - name: childInfo

  childInfo:
    nextScreens:
      - name: addChild
        condition: org.formflowstartertemplate.app.submission.conditions.HasChildren
      - name: protectiveServices

  endOfWorkflow:
    nextScreens: null

  addChild:
    subflow: children
    nextScreens:
      - name: reviewChildren

  reviewChildren:
    nextScreens:
      - name: otherChildrenNoCare

  otherChildrenNoCare:
    nextScreens:
      - name: protectiveServices

  protectiveServices:
    nextScreens:
      - name: workAndIncome

  addJob:
    subflow: jobs
    nextScreens:
      - name: reviewJobs

  jobDeleteConfirmation:
    nextScreens: null

  reviewJobs:
    nextScreens:
      - name: endOfWorkflow

  searchingForWork:
    nextScreens:
      - name: reviewTerms

  workAndIncome:
    nextScreens:
      - name: addJob
        condition: org.formflowstartertemplate.app.submission.conditions.HasJob
      - name: searchingForWork

  childDeleteConfirmation:
    nextScreens: null

  reviewTerms:
    nextScreens:
      - name: endOfWorkflow

subflows:
  children:
    entryScreen: childInfo
    iterationStartScreen: addChild
    reviewScreen: reviewChildren
    deleteConfirmationScreen: childDeleteConfirmation
  jobs:
    entryScreen: workAndIncome
    iterationStartScreen: addJob
    reviewScreen: reviewJobs
    deleteConfirmationScreen: jobDeleteConfirmation
---
name: ubi
conditionsPath: org.formflowstartertemplate.app.submission.conditions
actionsPath: org.formflowstartertemplate.app.submission.actions
flow:
  howThisWorks:
    nextScreens:
      - name: languagePreference
  languagePreference:
    nextScreens:
      - name: gettingToKnowYou
  gettingToKnowYou:
    nextScreens:
      - name: personalInfo
  personalInfo:
    nextScreens:
      - name: homeAddress
  homeAddress:
    nextScreens:
      - name: eligibility
  eligibility:
    nextScreens:
      - name: housemates
  housemates:
    nextScreens:
      - name: housemateInfo
        condition: org.formflowstartertemplate.app.submission.conditions.HasHousehold
      - name: income
  housemateInfo:
    subflow: household
    nextScreens:
      - name: householdList
  householdList:
    nextScreens:
      - name: income
  householdDeleteConfirmation:
    nextScreens: null
  income:
    nextScreens:
      - name: householdMemberIncome
  householdMemberIncome:
    subflow: income
    nextScreens:
      - name: incomeTypes
  incomeTypes:
    subflow: income
    nextScreens:
      - name: incomeAmounts
  incomeAmounts:
    beforeSave: org.formflowstartertemplate.app.submission.actions.ClearIncomeAmountsBeforeSaving
    subflow: income
    nextScreens:
      - name: annualHouseholdIncome
  annualHouseholdIncome:
    nextScreens:
      - name: incomeComplete
  incomeDeleteConfirmation:
    nextScreens: null
  reportedAnnualHouseholdIncome:
    nextScreens:
      - name: incomeComplete
  incomeComplete:
    nextScreens:
      - name: addingDocuments
  addingDocuments:
    nextScreens:
      - name: howToAddDocuments
  howToAddDocuments:
    nextScreens:
      - name: documentRecommendations
  documentRecommendations:
    nextScreens:
      - name: uploadUBIFlowDocuments
  documentOffboarding:
    nextScreens:
      - name: success
  uploadUBIFlowDocuments:
    nextScreens:
      - name: docSubmitConfirmation
  docSubmitConfirmation:
    nextScreens:
      - name: success
  success:
    nextScreens: null
subflows:
  household:
    entryScreen: housemates
    iterationStartScreen: housemateInfo
    reviewScreen: householdList
    deleteConfirmationScreen: householdDeleteConfirmation
  income:
    entryScreen: income
    iterationStartScreen: householdMemberIncome
    reviewScreen: annualHouseholdIncome
    deleteConfirmationScreen: incomeDeleteConfirmation
